# --- AFTER (PATCHED CODE | File: scripts/one_time_backfill.py) ---
import os
import io
import json
import pandas as pd
import re
from dotenv import load_dotenv
from supabase import create_client
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload

# [MODULE/CLASS SSOT ROLE]: One-Time Database Retrofitter
# [FUNCTION CONTRACT & MATH]: Reads GDrive CSVs, maps exact trades using absolute mathematical uniqueness (ID + Time + Qty), and backfills Set DNA into the Verification table.

# [TECHNICAL]: Load env vars and init Supabase client.
# [BUSINESS / DOMAIN LOGIC]: Establishes core connection to the database.
load_dotenv()
supabase = create_client(os.getenv("SUPABASE_URL"), os.getenv("SUPABASE_KEY"))

def run_backfill():
    # [TECHNICAL]: Authenticate with Google Drive API.
    # [BUSINESS / DOMAIN LOGIC]: Grants the script access to the CSVs generated by your trade downloader securely on the cloud.
    creds_info = json.loads(os.getenv("GDRIVE_SERVICE_ACCOUNT_JSON"))
    creds = service_account.Credentials.from_service_account_info(creds_info, scopes=['https://www.googleapis.com/auth/drive.readonly'])
    drive_service = build('drive', 'v3', credentials=creds)
    
    print("📡 Fetching existing verification rows...")
    all_db_rows = []
    offset = 0
    while True:
        res = supabase.table("strategy_trades_verification").select("id, strategy_id, trade_date, txn_time, txn_type, quantity").range(offset, offset + 999).execute()
        if not res.data: break
        all_db_rows.extend(res.data)
        offset += 1000

    # [TECHNICAL]: Creates an ultra-rigid dictionary mapping to guarantee we only update the exact row, preventing duplicates.
    db_map = {}
    for r in all_db_rows:
        try:
            # We use float formatting to normalize decimal discrepancies between pandas and supabase
            key = (str(r['strategy_id']), str(r['trade_date']), str(r['txn_time']), str(r['txn_type']), float(r['quantity']))
            db_map[key] = r['id']
        except Exception: pass
        
    print(f"🗺️ Mapped {len(db_map)} existing verification rows.")

    # [TECHNICAL]: Initialize update list and fetch folder ID.
    # [BUSINESS / DOMAIN LOGIC]: Prepares to batch the identified structural updates.
    updates = []
    source_folder = os.getenv("SOURCE_FOLDER")
    
    # [TECHNICAL]: Query Drive API for CSV files inside the target folder.
    # [BUSINESS / DOMAIN LOGIC]: Targets only the newly populated files downloaded by the GitHub runner.
    results = drive_service.files().list(q=f"'{source_folder}' in parents and mimeType='text/csv'", fields="files(id, name)").execute()
    files = results.get('files', [])
    
    for f in files:
        file_name = f['name']
        file_id = f['id']
        match = re.match(r'^(\d+)_', file_name)
        if not match: continue
        strat_id = match.group(1)
        
        try:
            # [TECHNICAL]: Download the file into a volatile RAM buffer instead of writing to disk.
            # [BUSINESS / DOMAIN LOGIC]: Securely reads the data without leaving artifacts on the CI/CD runner.
            request = drive_service.files().get_media(fileId=file_id)
            fh = io.BytesIO()
            downloader = MediaIoBaseDownload(fh, request)
            done = False
            while not done:
                status, done = downloader.next_chunk()
            fh.seek(0)
            
            df = pd.read_csv(fh)
            for _, row in df.iterrows():
                if pd.isna(row.iloc[4]): continue
                try:
                    raw_dt = pd.to_datetime(f"{row.iloc[14]} {row.iloc[15]}")
                    iso_date = raw_dt.strftime('%Y-%m-%d')
                    
                    # Account for %I stripping leading zeros on some platforms
                    hour_code = "%#I" if os.name == "nt" else "%-I"
                    formatted_time = raw_dt.strftime(f'%Y-%m-%d {hour_code}:%M:%S %p')
                    
                    qty_val = float(re.sub(r'[^\d.-]', '', str(row.iloc[16])))
                    txn_type = str(row.iloc[11]).strip()
                    
                    # [BUSINESS / DOMAIN LOGIC]: Looks up the exact row ID using the rigid mapping key.
                    key = (strat_id, iso_date, formatted_time, txn_type, qty_val)
                    if key in db_map:
                        db_id = db_map[key]
                        
                        updates.append({
                            "id": db_id,
                            "condition_type": str(row.iloc[12]).strip() if not pd.isna(row.iloc[12]) else None,
                            "condition_parent_id": str(row.iloc[24]).strip() if not pd.isna(row.iloc[24]) else None,
                            "condition_id": str(row.iloc[25]).strip() if not pd.isna(row.iloc[25]) else None
                        })
                except Exception: continue
        except Exception as e:
            print(f"⚠️ Failed to parse {file_name}: {e}")
    
    # [MODULE/CLASS SSOT ROLE]: One-Time Database Retrofitter Persistence Layer
    # [FUNCTION CONTRACT & MATH]: Executes targeted in-place column updates against exact row IDs safely, regardless of loop indentation.
    if updates:
        print(f"📤 Pushing {len(updates)} specific updates to Supabase via targeted updates...")
        success_count = 0
        for item in updates:
            # [TECHNICAL]: Extract target row ID non-destructively and isolate the payload via dictionary comprehension.
            # [BUSINESS / DOMAIN LOGIC]: Bypasses Postgres table INSERT NOT NULL constraints and prevents KeyError crashes if the loop accidentally executes multiple times over the same list.
            row_id = item["id"]
            payload = {k: v for k, v in item.items() if k != "id"}
            
            try:
                # [TECHNICAL]: Execute the targeted update using the isolated payload.
                # [BUSINESS / DOMAIN LOGIC]: Safely injects the Set DNA without touching other columns or failing constraints.
                supabase.table("strategy_trades_verification") \
                    .update(payload) \
                    .eq("id", row_id) \
                    .execute()
                success_count += 1
            except Exception as upd_err:
                print(f"⚠️ Failed to update row ID {row_id}: {upd_err}")
        print(f"✅ Backfill Complete. Successfully updated {success_count}/{len(updates)} rows.")
        
        # [TECHNICAL]: Force-clear the updates array immediately after a successful batch push.
        # [BUSINESS / DOMAIN LOGIC]: Guarantees that even if this block is accidentally indented inside the file-reading loop, previously pushed rows are deleted from memory and never double-processed.
        updates.clear()
    else:
        print("⚠️ No matching rows found to backfill.")

if __name__ == "__main__":
    run_backfill()